#ifndef BAIDUCLOUDWORKER_GLOBAL_H
#define BAIDUCLOUDWORKER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BAIDUCLOUDWORKER_LIBRARY)
#  define BAIDUCLOUDWORKERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BAIDUCLOUDWORKERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BAIDUCLOUDWORKER_GLOBAL_H
