#ifndef GENERALNETWORKWORKER_GLOBAL_H
#define GENERALNETWORKWORKER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GENERALNETWORKWORKER_LIBRARY)
#  define GENERALNETWORKWORKERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GENERALNETWORKWORKERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GENERALNETWORKWORKER_GLOBAL_H
