#ifndef CAPRICORNCORE_GLOBAL_H
#define CAPRICORNCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CAPRICORNCORE_LIBRARY)
#  define CAPRICORNCORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define CAPRICORNCORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CAPRICORNCORE_GLOBAL_H
